name: Merge PR to Main on Label

on:
  pull_request:
    branches:
      - dev
    types: ["closed"]

jobs:
  cherry_pick_to_main:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: ${{ contains(github.event.pull_request.labels.*.name, 'tested') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into main
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: main

      - name: Push changes
        run: |
          git push origin main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
