name: Merge PR to Main on Label

on:
  pull_request:
    types:
      - labeled

jobs:
  cherry_pick_to_main:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: ${{ contains(github.event.pull_request.labels.*.name, 'tested') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cherry pick into main
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: main

      - name: Remote View
        run: |
            git remote -v

      - name: Get the latest commit SHA
        id: get_sha
        run: echo "PR_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create a new branch for PR
        run: |
          git checkout -b pr-to-main-${{ env.PR_SHA }}
          git push origin pr-to-main-${{ env.PR_SHA }}

      - name: Create Pull Request from the cherry-picked commit to main
        env: 
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr create --base main --head pr-to-main-${{ env.PR_SHA }} --title "Auto Cherry-Pick: ${{ github.event.pull_request.head.ref }} to Main" --body "Automated PR to merge cherry-picked changes from ${{ github.event.pull_request.head.ref }} to main after passing QA."



env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
